Configurable opacity and mouse buttons
dbalatero/SkyRocket.spoon pull request #5
Opened 2021-12-12 13:45 UTC by cdump

I've made two changes:
1) configurable opacity for resize canvas, I prefer 0.75 in my configs
2) configurable mouse button for move/resize events - now it's possible to configure this spoon like https://awesomewm.org/
```
sky = SkyRocket:new({
  opacity = 0.75,
  moveModifiers = {'cmd'},
  moveMouseButton = 'left',
  resizeModifiers = {'cmd'},
  resizeMouseButton = 'right',
})
```

2021-12-12 20:38 UTC, dbalatero commented
Hi @cdump! Thanks for the PR. I am currently on vacation but I can look at this when I'm back at a computer after Dec 25!

2022-01-14 18:11 UTC, cdump commented
Hi @dbalatero! Did you get a chance to look into this?

2022-01-15 19:09 UTC, dbalatero requested changes
Hi @cdump! Thanks for sending this in, it's pretty clear and easy to follow.

A few comments for you to address, then I will test the branch locally and if it seems good I will approve the PR and merge!

2022-01-15 19:09 UTC, dbalatero commented on init.lua
> +    error('only "left" and "right" mouse button supported, got ' .. name)
**chore**: Please update this error message to include the name of the parameter that they misconfigured (`resizeMouseButton`)

2022-01-15 19:09 UTC, dbalatero commented on init.lua
> +    if name == 'left' then
**chore** Please match the local indentation style in this file (2 spaces), thanks!

2022-01-15 19:09 UTC, dbalatero commented on init.lua
> +        hs.eventtap.event.types.leftMouseDown,
**chore** 2 space indent, fix all cases (I won't comment this everywhere)

2022-01-15 19:09 UTC, dbalatero commented on init.lua
> +    local etype = event:getType()
**nit** Prefer expressive and clear variable names like `eventType`. Abbreviating `event` to `e` obscures what this variable is.

2022-01-15 19:09 UTC, dbalatero commented on init.lua
> +    moveStartMouseEvent = buttonNameToEventType(options.moveMouseButton or 'left'),
**praise** Thanks for keeping the defaults the same and not breaking past users.

2022-02-05 15:04 UTC, cdump commented
@dbalatero thanks for review, I've fixed all

2022-02-05 17:28 UTC, dbalatero approved these changes

2022-02-05 17:28 UTC, dbalatero commented
Awesome thank you! Tested it and still works on my end.

2022-02-05 17:28 UTC, merged